// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Steps in a migration.
public enum MigrationStep: Codable, Equatable, Sendable {
  /// Unspecified.
  case unspecified
  /// Start of migration.
  case start
  /// Data is copied to Cloud Firestore and then verified to match the data in
  /// Cloud Datastore.
  case copyAndVerify
  /// Eventually-consistent reads are redirected to Cloud Firestore.
  case redirectEventuallyConsistentReads
  /// Strongly-consistent reads are redirected to Cloud Firestore.
  case redirectStronglyConsistentReads
  /// Writes are redirected to Cloud Firestore.
  case redirectWrites
  /// Pre-migration: the database is prepared for migration.
  case prepare
  /// Writes are applied synchronously to at least one replica.
  case applyWritesSynchronously
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .start: return 1
    case .copyAndVerify: return 2
    case .redirectEventuallyConsistentReads: return 3
    case .redirectStronglyConsistentReads: return 4
    case .redirectWrites: return 5
    case .prepare: return 6
    case .applyWritesSynchronously: return 7
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: String? {
    switch self {
    case .unspecified: return "MIGRATION_STEP_UNSPECIFIED"
    case .start: return "START"
    case .copyAndVerify: return "COPY_AND_VERIFY"
    case .redirectEventuallyConsistentReads: return "REDIRECT_EVENTUALLY_CONSISTENT_READS"
    case .redirectStronglyConsistentReads: return "REDIRECT_STRONGLY_CONSISTENT_READS"
    case .redirectWrites: return "REDIRECT_WRITES"
    case .prepare: return "PREPARE"
    case .applyWritesSynchronously: return "APPLY_WRITES_SYNCHRONOUSLY"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
  public init(stringValue: String) {
    switch stringValue {
    case "MIGRATION_STEP_UNSPECIFIED": self = .unspecified
    case "PREPARE": self = .prepare
    case "START": self = .start
    case "APPLY_WRITES_SYNCHRONOUSLY": self = .applyWritesSynchronously
    case "COPY_AND_VERIFY": self = .copyAndVerify
    case "REDIRECT_EVENTUALLY_CONSISTENT_READS": self = .redirectEventuallyConsistentReads
    case "REDIRECT_STRONGLY_CONSISTENT_READS": self = .redirectStronglyConsistentReads
    case "REDIRECT_WRITES": self = .redirectWrites
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 6: self = .prepare
    case 1: self = .start
    case 7: self = .applyWritesSynchronously
    case 2: self = .copyAndVerify
    case 3: self = .redirectEventuallyConsistentReads
    case 4: self = .redirectStronglyConsistentReads
    case 5: self = .redirectWrites
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .start: return try container.encode(1)
    case .copyAndVerify: return try container.encode(2)
    case .redirectEventuallyConsistentReads: return try container.encode(3)
    case .redirectStronglyConsistentReads: return try container.encode(4)
    case .redirectWrites: return try container.encode(5)
    case .prepare: return try container.encode(6)
    case .applyWritesSynchronously: return try container.encode(7)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
