// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Metadata common to all Datastore Admin operations.
public struct CommonMetadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The time that work began on the operation.
  public var startTime: GoogleCloudWkt.Timestamp? = nil

  /// The time the operation ended, either successfully or otherwise.
  public var endTime: GoogleCloudWkt.Timestamp? = nil

  /// The type of the operation. Can be used as a filter in
  /// ListOperationsRequest.
  public var operationType: OperationType = OperationType()

  /// The client-assigned labels which were provided when the operation was
  /// created. May also include additional labels.
  public var labels: [Swift.String: Swift.String] = [:]

  /// The current state of the Operation.
  public var state: CommonMetadata.State = CommonMetadata.State()

  /// Initialize a new instance of `CommonMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CommonMetadata().with { $0.startTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The various possible states for an ongoing Operation.
  public enum State: Codable, Equatable, Sendable {
    /// Unspecified.
    case unspecified
    /// Request is being prepared for processing.
    case initializing
    /// Request is actively being processed.
    case processing
    /// Request is in the process of being cancelled after user called
    /// google.longrunning.Operations.CancelOperation on the operation.
    case cancelling
    /// Request has been processed and is in its finalization stage.
    case finalizing
    /// Request has completed successfully.
    case successful
    /// Request has finished being processed, but encountered an error.
    case failed
    /// Request has finished being cancelled after user called
    /// google.longrunning.Operations.CancelOperation.
    case cancelled
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .initializing: return 1
      case .processing: return 2
      case .cancelling: return 3
      case .finalizing: return 4
      case .successful: return 5
      case .failed: return 6
      case .cancelled: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .initializing: return "INITIALIZING"
      case .processing: return "PROCESSING"
      case .cancelling: return "CANCELLING"
      case .finalizing: return "FINALIZING"
      case .successful: return "SUCCESSFUL"
      case .failed: return "FAILED"
      case .cancelled: return "CANCELLED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "INITIALIZING": self = .initializing
      case "PROCESSING": self = .processing
      case "CANCELLING": self = .cancelling
      case "FINALIZING": self = .finalizing
      case "SUCCESSFUL": self = .successful
      case "FAILED": self = .failed
      case "CANCELLED": self = .cancelled
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .initializing
      case 2: self = .processing
      case 3: self = .cancelling
      case 4: self = .finalizing
      case 5: self = .successful
      case 6: self = .failed
      case 7: self = .cancelled
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .initializing: return try container.encode(1)
      case .processing: return try container.encode(2)
      case .cancelling: return try container.encode(3)
      case .finalizing: return try container.encode(4)
      case .successful: return try container.encode(5)
      case .failed: return try container.encode(6)
      case .cancelled: return try container.encode(7)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.datastore.admin.v1.CommonMetadata"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
