// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax

extension Clients {
  protocol DatastoreAdminStub: Sendable {
    func exportEntities(
      request: ExportEntitiesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func importEntities(
      request: ImportEntitiesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createIndex(
      request: CreateIndexRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteIndex(
      request: DeleteIndexRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getIndex(
      request: GetIndexRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDatastoreAdminV1.Index

    func listIndexes(
      request: ListIndexesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDatastoreAdminV1.ListIndexesResponse

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}
