// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// Google Cloud Datastore Admin API
///
/// The Datastore Admin API provides several admin services for Cloud Datastore.
///
/// Concepts: Project, namespace, kind, and entity as defined in the Google Cloud
/// Datastore API.
///
/// Operation: An Operation represents work being performed in the background.
///
/// EntityFilter: Allows specifying a subset of entities in a project. This is
/// specified as a combination of kinds and namespaces (either or both of which
/// may be all).
///
/// Export/Import Service:
///
/// - The Export/Import service provides the ability to copy all or a subset of
/// entities to/from Google Cloud Storage.
/// - Exported data may be imported into Cloud Datastore for any Google Cloud
/// Platform project. It is not restricted to the export source project. It is
/// possible to export from one project and then import into another.
/// - Exported data can also be loaded into Google BigQuery for analysis.
/// - Exports and imports are performed asynchronously. An Operation resource is
/// created for each export/import. The state (including any errors encountered)
/// of the export/import may be queried via the Operation resource.
///
/// Index Service:
///
/// - The index service manages Cloud Datastore composite indexes.
/// - Index creation and deletion are performed asynchronously.
/// An Operation resource is created for each such asynchronous operation.
/// The state of the operation (including any errors encountered)
/// may be queried via the Operation resource.
///
/// Operation Service:
///
/// - The Operations collection provides a record of actions performed for the
/// specified project (including any operations in progress). Operations are not
/// created directly but through calls on other collections or resources.
/// - An operation that is not yet done may be cancelled. The request to cancel
/// is asynchronous and the operation may continue to run for some time after the
/// request to cancel is made.
/// - An operation that is done may be deleted so that it is no longer listed as
/// part of the Operation collection.
/// - ListOperations returns all pending operations, but not completed
/// operations.
/// - Operations are created by service DatastoreAdmin, but are accessed via
/// service google.longrunning.Operations.
///
/// @Snippet(path: "DatastoreAdminQuickstart")
public class DatastoreAdminClient: Clients.DatastoreAdminProtocol {
  let inner: any Clients.DatastoreAdminStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `DatastoreAdminClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.DatastoreAdminStub = try Clients.DatastoreAdminTransport(options)
    inner = Clients.DatastoreAdminRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.DatastoreAdminLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Exports a copy of all or a subset of entities from Google Cloud Datastore
  /// to another storage system, such as Google Cloud Storage. Recent updates to
  /// entities may not be reflected in the export. The export occurs in the
  /// background and its progress can be monitored and managed via the
  /// Operation resource that is created. The output of an export may only be
  /// used once the associated operation is done. If an export operation is
  /// cancelled before completion it may leave partial data behind in Google
  /// Cloud Storage.
  ///
  /// @Snippet(path: "DatastoreAdmin_ExportEntities")
  public func exportEntities(
    request: ExportEntitiesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.exportEntities(request: request, options: options)
  }

  /// Exports a copy of all or a subset of entities from Google Cloud Datastore
  /// to another storage system, such as Google Cloud Storage. Recent updates to
  /// entities may not be reflected in the export. The export occurs in the
  /// background and its progress can be monitored and managed via the
  /// Operation resource that is created. The output of an export may only be
  /// used once the associated operation is done. If an export operation is
  /// cancelled before completion it may leave partial data behind in Google
  /// Cloud Storage.
  ///
  /// @Snippet(path: "DatastoreAdmin_ExportEntities")
  public func exportEntities(
    withPolling: ExportEntitiesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<ExportEntitiesResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<ExportEntitiesResponse>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try ExportEntitiesResponse(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.exportEntities(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<ExportEntitiesResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Imports entities into Google Cloud Datastore. Existing entities with the
  /// same key are overwritten. The import occurs in the background and its
  /// progress can be monitored and managed via the Operation resource that is
  /// created. If an ImportEntities operation is cancelled, it is possible
  /// that a subset of the data has already been imported to Cloud Datastore.
  ///
  /// @Snippet(path: "DatastoreAdmin_ImportEntities")
  public func importEntities(
    request: ImportEntitiesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.importEntities(request: request, options: options)
  }

  /// Imports entities into Google Cloud Datastore. Existing entities with the
  /// same key are overwritten. The import occurs in the background and its
  /// progress can be monitored and managed via the Operation resource that is
  /// created. If an ImportEntities operation is cancelled, it is possible
  /// that a subset of the data has already been imported to Cloud Datastore.
  ///
  /// @Snippet(path: "DatastoreAdmin_ImportEntities")
  public func importEntities(
    withPolling: ImportEntitiesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Void>.State
      in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response:
        return .init(done: true, result: .success(()))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.importEntities(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Creates the specified index.
  /// A newly created index's initial state is `CREATING`. On completion of the
  /// returned [google.longrunning.Operation][google.longrunning.Operation], the
  /// state will be `READY`. If the index already exists, the call will return an
  /// `ALREADY_EXISTS` status.
  ///
  /// During index creation, the process could result in an error, in which
  /// case the index will move to the `ERROR` state. The process can be recovered
  /// by fixing the data that caused the error, removing the index with
  /// [delete][google.datastore.admin.v1.DatastoreAdmin.DeleteIndex], then
  /// re-creating the index with [create]
  /// [google.datastore.admin.v1.DatastoreAdmin.CreateIndex].
  ///
  /// Indexes with a single property cannot be created.
  ///
  /// [google.datastore.admin.v1.DatastoreAdmin.DeleteIndex]: <doc:DatastoreAdmin/deleteIndex(request:)>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "DatastoreAdmin_CreateIndex")
  public func createIndex(
    request: CreateIndexRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createIndex(request: request, options: options)
  }

  /// Creates the specified index.
  /// A newly created index's initial state is `CREATING`. On completion of the
  /// returned [google.longrunning.Operation][google.longrunning.Operation], the
  /// state will be `READY`. If the index already exists, the call will return an
  /// `ALREADY_EXISTS` status.
  ///
  /// During index creation, the process could result in an error, in which
  /// case the index will move to the `ERROR` state. The process can be recovered
  /// by fixing the data that caused the error, removing the index with
  /// [delete][google.datastore.admin.v1.DatastoreAdmin.DeleteIndex], then
  /// re-creating the index with [create]
  /// [google.datastore.admin.v1.DatastoreAdmin.CreateIndex].
  ///
  /// Indexes with a single property cannot be created.
  ///
  /// [google.datastore.admin.v1.DatastoreAdmin.DeleteIndex]: <doc:DatastoreAdmin/deleteIndex(request:)>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "DatastoreAdmin_CreateIndex")
  public func createIndex(
    withPolling: CreateIndexRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Index> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Index>.State
      in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Index(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.createIndex(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Index>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes an existing index.
  /// An index can only be deleted if it is in a `READY` or `ERROR` state. On
  /// successful execution of the request, the index will be in a `DELETING`
  /// [state][google.datastore.admin.v1.Index.State]. And on completion of the
  /// returned [google.longrunning.Operation][google.longrunning.Operation], the
  /// index will be removed.
  ///
  /// During index deletion, the process could result in an error, in which
  /// case the index will move to the `ERROR` state. The process can be recovered
  /// by fixing the data that caused the error, followed by calling
  /// [delete][google.datastore.admin.v1.DatastoreAdmin.DeleteIndex] again.
  ///
  /// [google.datastore.admin.v1.DatastoreAdmin.DeleteIndex]: <doc:DatastoreAdmin/deleteIndex(request:)>
  /// [google.datastore.admin.v1.Index.State]: <doc:Index/State>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "DatastoreAdmin_DeleteIndex")
  public func deleteIndex(
    request: DeleteIndexRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteIndex(request: request, options: options)
  }

  /// Deletes an existing index.
  /// An index can only be deleted if it is in a `READY` or `ERROR` state. On
  /// successful execution of the request, the index will be in a `DELETING`
  /// [state][google.datastore.admin.v1.Index.State]. And on completion of the
  /// returned [google.longrunning.Operation][google.longrunning.Operation], the
  /// index will be removed.
  ///
  /// During index deletion, the process could result in an error, in which
  /// case the index will move to the `ERROR` state. The process can be recovered
  /// by fixing the data that caused the error, followed by calling
  /// [delete][google.datastore.admin.v1.DatastoreAdmin.DeleteIndex] again.
  ///
  /// [google.datastore.admin.v1.DatastoreAdmin.DeleteIndex]: <doc:DatastoreAdmin/deleteIndex(request:)>
  /// [google.datastore.admin.v1.Index.State]: <doc:Index/State>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "DatastoreAdmin_DeleteIndex")
  public func deleteIndex(
    withPolling: DeleteIndexRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Index> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Index>.State
      in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Index(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.deleteIndex(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Index>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Gets an index.
  ///
  /// @Snippet(path: "DatastoreAdmin_GetIndex")
  public func getIndex(
    request: GetIndexRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatastoreAdminV1.Index {
    try await self.inner.getIndex(request: request, options: options)
  }

  /// Lists the indexes that match the specified filters.  Datastore uses an
  /// eventually consistent query to fetch the list of indexes and may
  /// occasionally return stale results.
  ///
  /// @Snippet(path: "DatastoreAdmin_ListIndexes")
  public func listIndexes(
    request: ListIndexesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatastoreAdminV1.ListIndexesResponse {
    try await self.inner.listIndexes(request: request, options: options)
  }

  /// Lists the indexes that match the specified filters.  Datastore uses an
  /// eventually consistent query to fetch the list of indexes and may
  /// occasionally return stale results.
  ///
  /// @Snippet(path: "DatastoreAdmin_ListIndexes")
  public func listIndexes(
    byItem: ListIndexesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Index, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudDatastoreAdminV1.ListIndexesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listIndexes(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "DatastoreAdmin_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "DatastoreAdmin_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "DatastoreAdmin_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "DatastoreAdmin_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "DatastoreAdmin_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `DatastoreAdminClient`.
  ///
  /// To mock `DatastoreAdminClient` change your functions to receive
  /// `some DatastoreAdminProtocol` or `any DatastoreAdminProtocol`
  /// and pass a mock implementation in your tests.
  public protocol DatastoreAdminProtocol {
    /// See `DatastoreAdminClient.exportEntities`.
    func exportEntities(request: ExportEntitiesRequest) async throws -> GoogleLongRunning.Operation

    /// See `DatastoreAdminClient.exportEntities`.
    func exportEntities(withPolling: ExportEntitiesRequest) async throws -> any GoogleCloudGax
      .PollableOperation<ExportEntitiesResponse>

    /// See `DatastoreAdminClient.exportEntities`.
    func exportEntities(
      projectId: Swift.String,
      labels: [Swift.String: Swift.String],
      entityFilter: EntityFilter?,
      outputUrlPrefix: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<ExportEntitiesResponse>

    /// See `DatastoreAdminClient.importEntities`.
    func importEntities(request: ImportEntitiesRequest) async throws -> GoogleLongRunning.Operation

    /// See `DatastoreAdminClient.importEntities`.
    func importEntities(withPolling: ImportEntitiesRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Void>

    /// See `DatastoreAdminClient.importEntities`.
    func importEntities(
      projectId: Swift.String,
      labels: [Swift.String: Swift.String],
      inputUrl: Swift.String,
      entityFilter: EntityFilter?,
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `DatastoreAdminClient.createIndex`.
    func createIndex(request: CreateIndexRequest) async throws -> GoogleLongRunning.Operation

    /// See `DatastoreAdminClient.createIndex`.
    func createIndex(withPolling: CreateIndexRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Index>

    /// See `DatastoreAdminClient.deleteIndex`.
    func deleteIndex(request: DeleteIndexRequest) async throws -> GoogleLongRunning.Operation

    /// See `DatastoreAdminClient.deleteIndex`.
    func deleteIndex(withPolling: DeleteIndexRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Index>

    /// See `DatastoreAdminClient.getIndex`.
    func getIndex(request: GetIndexRequest) async throws -> GoogleCloudDatastoreAdminV1.Index

    /// See `DatastoreAdminClient.listIndexes`.
    func listIndexes(request: ListIndexesRequest) async throws
      -> GoogleCloudDatastoreAdminV1.ListIndexesResponse

    /// See `DatastoreAdminClient.listIndexes`.
    func listIndexes(
      byItem: ListIndexesRequest
    ) throws -> any AsyncSequence<Index, Swift.Error>

    /// See `DatastoreAdminClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `DatastoreAdminClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `DatastoreAdminClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `DatastoreAdminClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `DatastoreAdminClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `DatastoreAdminClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `DatastoreAdminClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `DatastoreAdminClient.exportEntities`.
    func exportEntities(
      request: ExportEntitiesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DatastoreAdminClient.exportEntities`.
    func exportEntities(
      withPolling: ExportEntitiesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<ExportEntitiesResponse>

    /// See `DatastoreAdminClient.importEntities`.
    func importEntities(
      request: ImportEntitiesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DatastoreAdminClient.importEntities`.
    func importEntities(
      withPolling: ImportEntitiesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `DatastoreAdminClient.createIndex`.
    func createIndex(
      request: CreateIndexRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DatastoreAdminClient.createIndex`.
    func createIndex(
      withPolling: CreateIndexRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Index>

    /// See `DatastoreAdminClient.deleteIndex`.
    func deleteIndex(
      request: DeleteIndexRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DatastoreAdminClient.deleteIndex`.
    func deleteIndex(
      withPolling: DeleteIndexRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Index>

    /// See `DatastoreAdminClient.getIndex`.
    func getIndex(
      request: GetIndexRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastoreAdminV1.Index

    /// See `DatastoreAdminClient.listIndexes`.
    func listIndexes(
      request: ListIndexesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastoreAdminV1.ListIndexesResponse

    /// See `DatastoreAdminClient.listIndexes`.
    func listIndexes(
      byItem: ListIndexesRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Index, Swift.Error>

    /// See `DatastoreAdminClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `DatastoreAdminClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `DatastoreAdminClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `DatastoreAdminClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.DatastoreAdminProtocol {
  public func exportEntities(request: ExportEntitiesRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.exportEntities(request: request, options: .init())
  }

  public func exportEntities(
    request: ExportEntitiesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func exportEntities(withPolling: ExportEntitiesRequest) async throws -> any GoogleCloudGax
    .PollableOperation<ExportEntitiesResponse>
  {
    try await self.exportEntities(withPolling: withPolling, options: .init())
  }

  public func exportEntities(
    withPolling: ExportEntitiesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<ExportEntitiesResponse> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<ExportEntitiesResponse>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func exportEntities(
    projectId: Swift.String,
    labels: [Swift.String: Swift.String],
    entityFilter: EntityFilter?,
    outputUrlPrefix: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<ExportEntitiesResponse> {
    let request = ExportEntitiesRequest().with {
      $0.projectId = projectId
      $0.labels = labels
      $0.entityFilter = entityFilter
      $0.outputUrlPrefix = outputUrlPrefix
    }
    return try await self.exportEntities(withPolling: request)
  }

  public func importEntities(request: ImportEntitiesRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.importEntities(request: request, options: .init())
  }

  public func importEntities(
    request: ImportEntitiesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func importEntities(withPolling: ImportEntitiesRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Void>
  {
    try await self.importEntities(withPolling: withPolling, options: .init())
  }

  public func importEntities(
    withPolling: ImportEntitiesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func importEntities(
    projectId: Swift.String,
    labels: [Swift.String: Swift.String],
    inputUrl: Swift.String,
    entityFilter: EntityFilter?,
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let request = ImportEntitiesRequest().with {
      $0.projectId = projectId
      $0.labels = labels
      $0.inputUrl = inputUrl
      $0.entityFilter = entityFilter
    }
    return try await self.importEntities(withPolling: request)
  }

  public func createIndex(request: CreateIndexRequest) async throws -> GoogleLongRunning.Operation {
    try await self.createIndex(request: request, options: .init())
  }

  public func createIndex(
    request: CreateIndexRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createIndex(withPolling: CreateIndexRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Index>
  {
    try await self.createIndex(withPolling: withPolling, options: .init())
  }

  public func createIndex(
    withPolling: CreateIndexRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Index> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Index>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteIndex(request: DeleteIndexRequest) async throws -> GoogleLongRunning.Operation {
    try await self.deleteIndex(request: request, options: .init())
  }

  public func deleteIndex(
    request: DeleteIndexRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteIndex(withPolling: DeleteIndexRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Index>
  {
    try await self.deleteIndex(withPolling: withPolling, options: .init())
  }

  public func deleteIndex(
    withPolling: DeleteIndexRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Index> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Index>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func getIndex(request: GetIndexRequest) async throws -> GoogleCloudDatastoreAdminV1.Index {
    try await self.getIndex(request: request, options: .init())
  }

  public func getIndex(
    request: GetIndexRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatastoreAdminV1.Index {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listIndexes(request: ListIndexesRequest) async throws
    -> GoogleCloudDatastoreAdminV1.ListIndexesResponse
  {
    try await self.listIndexes(request: request, options: .init())
  }

  public func listIndexes(
    request: ListIndexesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatastoreAdminV1.ListIndexesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listIndexes(
    byItem: ListIndexesRequest
  ) throws -> any AsyncSequence<Index, Swift.Error> {
    try self.listIndexes(byItem: byItem, options: .init())
  }

  public func listIndexes(
    byItem: ListIndexesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Index, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudDatastoreAdminV1.ListIndexesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
