// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Metadata for ExportEntities operations.
public struct ExportEntitiesMetadata: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Metadata common to all Datastore Admin operations.
  public var common: CommonMetadata? = nil

  /// An estimate of the number of entities processed.
  public var progressEntities: Progress? = nil

  /// An estimate of the number of bytes processed.
  public var progressBytes: Progress? = nil

  /// Description of which entities are being exported.
  public var entityFilter: EntityFilter? = nil

  /// Location for the export metadata and data files. This will be the same
  /// value as the
  /// [google.datastore.admin.v1.ExportEntitiesRequest.output_url_prefix][google.datastore.admin.v1.ExportEntitiesRequest.output_url_prefix]
  /// field. The final output location is provided in
  /// [google.datastore.admin.v1.ExportEntitiesResponse.output_url][google.datastore.admin.v1.ExportEntitiesResponse.output_url].
  ///
  /// [google.datastore.admin.v1.ExportEntitiesRequest.output_url_prefix]: <doc:ExportEntitiesRequest/outputUrlPrefix>
  /// [google.datastore.admin.v1.ExportEntitiesResponse.output_url]: <doc:ExportEntitiesResponse/outputUrl>
  public var outputUrlPrefix: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ExportEntitiesMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ExportEntitiesMetadata().with { $0.common = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let common = CodingKeys(stringValue: "common")
    static let progressEntities = CodingKeys(stringValue: "progressEntities")
    static let progressBytes = CodingKeys(stringValue: "progressBytes")
    static let entityFilter = CodingKeys(stringValue: "entityFilter")
    static let outputUrlPrefix = CodingKeys(stringValue: "outputUrlPrefix")

    static let _knownKeys: Set<Swift.String> = [
      "common",
      "progressEntities",
      "progressBytes",
      "entityFilter",
      "outputUrlPrefix",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.common = try container.decodeIfPresent(CommonMetadata.self, forKey: .common)
    self.progressEntities = try container.decodeIfPresent(Progress.self, forKey: .progressEntities)
    self.progressBytes = try container.decodeIfPresent(Progress.self, forKey: .progressBytes)
    self.entityFilter = try container.decodeIfPresent(EntityFilter.self, forKey: .entityFilter)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .outputUrlPrefix) {
      self.outputUrlPrefix = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.common, forKey: .common)
    try container.encodeIfPresent(self.progressEntities, forKey: .progressEntities)
    try container.encodeIfPresent(self.progressBytes, forKey: .progressBytes)
    try container.encodeIfPresent(self.entityFilter, forKey: .entityFilter)
    try container.encode(self.outputUrlPrefix, forKey: .outputUrlPrefix)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.datastore.admin.v1.ExportEntitiesMetadata"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
