// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Metadata for ExportEntities operations.
public struct ExportEntitiesMetadata: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Metadata common to all Datastore Admin operations.
  public var common: CommonMetadata? = nil

  /// An estimate of the number of entities processed.
  public var progressEntities: Progress? = nil

  /// An estimate of the number of bytes processed.
  public var progressBytes: Progress? = nil

  /// Description of which entities are being exported.
  public var entityFilter: EntityFilter? = nil

  /// Location for the export metadata and data files. This will be the same
  /// value as the
  /// [google.datastore.admin.v1.ExportEntitiesRequest.output_url_prefix][google.datastore.admin.v1.ExportEntitiesRequest.output_url_prefix]
  /// field. The final output location is provided in
  /// [google.datastore.admin.v1.ExportEntitiesResponse.output_url][google.datastore.admin.v1.ExportEntitiesResponse.output_url].
  ///
  /// [google.datastore.admin.v1.ExportEntitiesRequest.output_url_prefix]: <doc:ExportEntitiesRequest/outputUrlPrefix>
  /// [google.datastore.admin.v1.ExportEntitiesResponse.output_url]: <doc:ExportEntitiesResponse/outputUrl>
  public var outputUrlPrefix: Swift.String = Swift.String()

  /// Initialize a new instance of `ExportEntitiesMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ExportEntitiesMetadata().with { $0.common = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.datastore.admin.v1.ExportEntitiesMetadata"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
