// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// An event signifying the start of a new step in a [migration from Cloud
/// Datastore to Cloud Firestore in Datastore
/// mode](https://cloud.google.com/datastore/docs/upgrade-to-firestore).
public struct MigrationProgressEvent: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The step that is starting.
  ///
  /// An event with step set to `START` indicates that the migration
  /// has been reverted back to the initial pre-migration state.
  public var step: MigrationStep = MigrationStep()

  /// Details about this step.
  public var stepDetails: OneOf_StepDetails? = nil

  /// Initialize a new instance of `MigrationProgressEvent`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MigrationProgressEvent().with { $0.step = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case step = "step"
    case prepareStepDetails = "prepareStepDetails"
    case redirectWritesStepDetails = "redirectWritesStepDetails"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.step = try container.decode(MigrationStep.self, forKey: .step)

    var stepDetails: OneOf_StepDetails? = nil
    let stepDetailsCheckAndSet = {
      if stepDetails != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'stepDetails'"))
      }
      stepDetails = $0
    }
    if let prepareStepDetails = try container.decodeIfPresent(
      MigrationProgressEvent.PrepareStepDetails?.self, forKey: .prepareStepDetails)
    {
      try stepDetailsCheckAndSet(.prepareStepDetails(prepareStepDetails))
    }
    if let redirectWritesStepDetails = try container.decodeIfPresent(
      MigrationProgressEvent.RedirectWritesStepDetails?.self, forKey: .redirectWritesStepDetails)
    {
      try stepDetailsCheckAndSet(.redirectWritesStepDetails(redirectWritesStepDetails))
    }
    self.stepDetails = stepDetails
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.step, forKey: .step)

    if let choice = self.stepDetails {
      switch choice {
      case .prepareStepDetails(let value):
        try container.encode(value, forKey: .prepareStepDetails)
      case .redirectWritesStepDetails(let value):
        try container.encode(value, forKey: .redirectWritesStepDetails)
      }
    }
  }

  /// Details for the `PREPARE` step.
  public struct PrepareStepDetails: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The concurrency mode this database will use when it reaches the
    /// `REDIRECT_WRITES` step.
    public var concurrencyMode: MigrationProgressEvent.ConcurrencyMode =
      MigrationProgressEvent.ConcurrencyMode()

    /// Initialize a new instance of `PrepareStepDetails`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PrepareStepDetails().with { $0.concurrencyMode = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.datastore.admin.v1.MigrationProgressEvent.PrepareStepDetails"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Details for the `REDIRECT_WRITES` step.
  public struct RedirectWritesStepDetails: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Ths concurrency mode for this database.
    public var concurrencyMode: MigrationProgressEvent.ConcurrencyMode =
      MigrationProgressEvent.ConcurrencyMode()

    /// Initialize a new instance of `RedirectWritesStepDetails`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RedirectWritesStepDetails().with { $0.concurrencyMode = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.datastore.admin.v1.MigrationProgressEvent.RedirectWritesStepDetails"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Concurrency modes for transactions in Cloud Firestore.
  public enum ConcurrencyMode: Codable, Equatable, Sendable {
    /// Unspecified.
    case unspecified
    /// Pessimistic concurrency.
    case pessimistic
    /// Optimistic concurrency.
    case optimistic
    /// Optimistic concurrency with entity groups.
    case optimisticWithEntityGroups
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .pessimistic: return 1
      case .optimistic: return 2
      case .optimisticWithEntityGroups: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CONCURRENCY_MODE_UNSPECIFIED"
      case .pessimistic: return "PESSIMISTIC"
      case .optimistic: return "OPTIMISTIC"
      case .optimisticWithEntityGroups: return "OPTIMISTIC_WITH_ENTITY_GROUPS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ConcurrencyMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CONCURRENCY_MODE_UNSPECIFIED": self = .unspecified
      case "PESSIMISTIC": self = .pessimistic
      case "OPTIMISTIC": self = .optimistic
      case "OPTIMISTIC_WITH_ENTITY_GROUPS": self = .optimisticWithEntityGroups
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ConcurrencyMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .pessimistic
      case 2: self = .optimistic
      case 3: self = .optimisticWithEntityGroups
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .pessimistic: return try container.encode(1)
      case .optimistic: return try container.encode(2)
      case .optimisticWithEntityGroups: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Details about this step.
  public enum OneOf_StepDetails: Codable, Equatable, Sendable {
    /// Details for the `PREPARE` step.
    indirect case prepareStepDetails(MigrationProgressEvent.PrepareStepDetails?)
    /// Details for the `REDIRECT_WRITES` step.
    indirect case redirectWritesStepDetails(MigrationProgressEvent.RedirectWritesStepDetails?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.datastore.admin.v1.MigrationProgressEvent"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
