// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// An event signifying the start of a new step in a [migration from Cloud
/// Datastore to Cloud Firestore in Datastore
/// mode](https://cloud.google.com/datastore/docs/upgrade-to-firestore).
public struct MigrationProgressEvent: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The step that is starting.
  ///
  /// An event with step set to `START` indicates that the migration
  /// has been reverted back to the initial pre-migration state.
  public var step: MigrationStep = MigrationStep()

  /// Details about this step.
  public var stepDetails: StepDetailsOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `MigrationProgressEvent`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MigrationProgressEvent().with { $0.step = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let step = CodingKeys(stringValue: "step")
    static let prepareStepDetails = CodingKeys(stringValue: "prepareStepDetails")
    static let redirectWritesStepDetails = CodingKeys(stringValue: "redirectWritesStepDetails")

    static let _knownKeys: Set<Swift.String> = [
      "step",
      "prepareStepDetails",
      "redirectWritesStepDetails",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(MigrationStep.self, forKey: .step) {
      self.step = value
    }

    var stepDetails: StepDetailsOneOf? = nil
    let stepDetailsCheckAndSet = {
      if stepDetails != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'stepDetails'"))
      }
      stepDetails = $0
    }
    if let prepareStepDetails = try container.decodeIfPresent(
      MigrationProgressEvent.PrepareStepDetails?.self, forKey: .prepareStepDetails)
    {
      try stepDetailsCheckAndSet(.prepareStepDetails(prepareStepDetails))
    }
    if let redirectWritesStepDetails = try container.decodeIfPresent(
      MigrationProgressEvent.RedirectWritesStepDetails?.self, forKey: .redirectWritesStepDetails)
    {
      try stepDetailsCheckAndSet(.redirectWritesStepDetails(redirectWritesStepDetails))
    }
    self.stepDetails = stepDetails
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.step, forKey: .step)

    if let choice = self.stepDetails {
      switch choice {
      case .prepareStepDetails(let value):
        try container.encode(value, forKey: .prepareStepDetails)
      case .redirectWritesStepDetails(let value):
        try container.encode(value, forKey: .redirectWritesStepDetails)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Details for the `PREPARE` step.
  public struct PrepareStepDetails: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The concurrency mode this database will use when it reaches the
    /// `REDIRECT_WRITES` step.
    public var concurrencyMode: MigrationProgressEvent.ConcurrencyMode =
      MigrationProgressEvent.ConcurrencyMode()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `PrepareStepDetails`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PrepareStepDetails().with { $0.concurrencyMode = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let concurrencyMode = CodingKeys(stringValue: "concurrencyMode")

      static let _knownKeys: Set<Swift.String> = [
        "concurrencyMode"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        MigrationProgressEvent.ConcurrencyMode.self, forKey: .concurrencyMode)
      {
        self.concurrencyMode = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.concurrencyMode, forKey: .concurrencyMode)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.datastore.admin.v1.MigrationProgressEvent.PrepareStepDetails"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Details for the `REDIRECT_WRITES` step.
  public struct RedirectWritesStepDetails: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Ths concurrency mode for this database.
    public var concurrencyMode: MigrationProgressEvent.ConcurrencyMode =
      MigrationProgressEvent.ConcurrencyMode()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `RedirectWritesStepDetails`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RedirectWritesStepDetails().with { $0.concurrencyMode = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let concurrencyMode = CodingKeys(stringValue: "concurrencyMode")

      static let _knownKeys: Set<Swift.String> = [
        "concurrencyMode"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        MigrationProgressEvent.ConcurrencyMode.self, forKey: .concurrencyMode)
      {
        self.concurrencyMode = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.concurrencyMode, forKey: .concurrencyMode)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.datastore.admin.v1.MigrationProgressEvent.RedirectWritesStepDetails"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Concurrency modes for transactions in Cloud Firestore.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum ConcurrencyMode: Codable, Equatable, Hashable, Sendable {
    /// Unspecified.
    case unspecified
    /// Pessimistic concurrency.
    case pessimistic
    /// Optimistic concurrency.
    case optimistic
    /// Optimistic concurrency with entity groups.
    case optimisticWithEntityGroups
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .pessimistic: return 1
      case .optimistic: return 2
      case .optimisticWithEntityGroups: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CONCURRENCY_MODE_UNSPECIFIED"
      case .pessimistic: return "PESSIMISTIC"
      case .optimistic: return "OPTIMISTIC"
      case .optimisticWithEntityGroups: return "OPTIMISTIC_WITH_ENTITY_GROUPS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ConcurrencyMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CONCURRENCY_MODE_UNSPECIFIED": self = .unspecified
      case "PESSIMISTIC": self = .pessimistic
      case "OPTIMISTIC": self = .optimistic
      case "OPTIMISTIC_WITH_ENTITY_GROUPS": self = .optimisticWithEntityGroups
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ConcurrencyMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .pessimistic
      case 2: self = .optimistic
      case 3: self = .optimisticWithEntityGroups
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("CONCURRENCY_MODE_UNSPECIFIED")
      case .pessimistic: return try container.encode("PESSIMISTIC")
      case .optimistic: return try container.encode("OPTIMISTIC")
      case .optimisticWithEntityGroups: return try container.encode("OPTIMISTIC_WITH_ENTITY_GROUPS")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Details about this step.
  public enum StepDetailsOneOf: Codable, Equatable, Sendable {
    /// Details for the `PREPARE` step.
    indirect case prepareStepDetails(MigrationProgressEvent.PrepareStepDetails?)
    /// Details for the `REDIRECT_WRITES` step.
    indirect case redirectWritesStepDetails(MigrationProgressEvent.RedirectWritesStepDetails?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.datastore.admin.v1.MigrationProgressEvent"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
